class COD_556x45mm_Friendly : COD_Projectile
{
	Default
	{
		COD_Projectile.BaseDamage 30;
		COD_Projectile.RipperCount 3;
		Speed 107;
		Obituary "";
		COD_Projectile.FriendlyFire true;
	}
}

class COD_44Magnum_Friendly : COD_Projectile
{
	Default
	{
		COD_Projectile.BaseDamage 40;
		COD_Projectile.RipperCount 3;
		Speed 107;
		Obituary "";
		COD_Projectile.FriendlyFire true;
	}
}

class COD_9x19mm_Friendly : COD_Projectile
{
	Default
	{
		COD_Projectile.BaseDamage 27;
		COD_Projectile.RipperCount 2;
		Speed 107;
		Obituary "";
		COD_Projectile.FriendlyFire true;
	}
}

class COD_338Lapua_Friendly : COD_Projectile
{
	Default
	{
		COD_Projectile.BaseDamage 61;
		COD_Projectile.RipperCount 5;
		Speed 107;
		Obituary "";
		COD_Projectile.FriendlyFire true;
	}
}

class COD_762x51mm_Friendly : COD_Projectile
{
	Default
	{
		COD_Projectile.BaseDamage 36;
		COD_Projectile.RipperCount 4;
		Speed 107;
		Obituary "";
		COD_Projectile.FriendlyFire true;
	}
}