Class FollowerSpawnTauntHandler : EventHandler
{
	Override Void WorldThingDied(WorldEvent e)
	{
		Let victim = e.Thing;
		Let source = e.Thing.Target;		
		If((victim.bISMONSTER || victim.bCOUNTKILL) && source is "Follower_Sakuya")
		{
			If(Source && Source.Health > 0)			
			{
				If(Random(0,100) <= 10 || Victim.bBOSS) 
				{ 
					Source.A_StartSound("Sakuya/Idle",CHAN_VOICE);
				}
			}
		}
		If((victim.bISMONSTER || victim.bCOUNTKILL) && source is "Follower_Meryl")
		{
			If(Source && Source.Health > 0)			
			{
				If(Random(0,100) <= 10 || Victim.bBOSS) 
				{ 
					Source.A_StartSound("Meryl/Idle",CHAN_VOICE);
				}
			}
		}
		If((victim.bISMONSTER || victim.bCOUNTKILL) && source is "Follower_Iris")
		{
			If(Source && Source.Health > 0)			
			{
				If(Random(0,100) <= 10 || Victim.bBOSS) 
				{ 
					Source.A_StartSound("Iris/Idle",CHAN_VOICE);
				}
			}
		}
	}
	
	Override Void PlayerEntered(PlayerEvent e)
	{
		Let pl = players[e.PlayerNumber].mo;
		
		//[Pop] We are about to have gross hacks and a bunch of If statements
		//only God may help us now.
		
		if(pl.CountInv("Follower_Sakuya_Token") == 1)
		{
			let SAKUYA = pl.Spawn("Follower_Sakuya",pl.pos,ALLOW_REPLACE);
			If(SAKUYA)
			{
				SAKUYA.Master = pl;
				SAKUYA.target = pl;
				//SAKUYA.Translation = pl.Translation;
				SAKUYA.A_FaceMaster();
			}
		}
		if(pl.CountInv("Follower_Meryl_Token") == 1)
		{
			let MERYL = pl.Spawn("Follower_Meryl",pl.pos,ALLOW_REPLACE);
			If(MERYL)
			{
				MERYL.Master = pl;
				MERYL.target = pl;
				//MERYL.Translation = pl.Translation;
				MERYL.A_FaceMaster();
			}
		}
		if(pl.CountInv("Follower_Iris_Token") == 1)
		{
			let IRIS = pl.Spawn("Follower_Iris",pl.pos,ALLOW_REPLACE);
			If(IRIS)
			{
				IRIS.Master = pl;
				IRIS.target = pl;
				//IRIS.Translation = pl.Translation;
				IRIS.A_FaceMaster();
			}
		}
		
		
		//[Pop] After checking all tokens and spawning them, alert in a small
		//radius just to activate them, just in case.
		pl.A_AlertMonsters(64);
	}
}