//#include "ZScript/Followers/Characters/UACTaskForce/blank.zsc"
//#include "ZScript/Followers/Characters/TaskForce141/blank.zsc"
//#include "ZScript/Followers/Characters/SOGTeam/blank.zsc"

//#include "ZScript/Followers/Characters/Ey.zsc"
#include "ZScript/Followers/Characters/Sakuya.zsc"
//#include "ZScript/Followers/Characters/Meiling.zsc"
//#include "ZScript/Followers/Characters/Maiko.zsc"
//#include "ZScript/Followers/Characters/Meryl.zsc"
//#include "ZScript/Followers/Characters/Iris.zsc"

class IMAFRIENDLYDIPSHIT : Inventory { Default { Inventory.MaxAmount 1; } }