class Follower_Iris : actor
{
	Int TeleTic;	
	Int	IdleTic;
	Int HealTimer;
	
	Int PrimAmmo;
	Int SecAmmo;
	
	bool SecondaryOut;
	bool SetIdle;
	
	Default
	{
		Monster;
		Health 125;
		Radius 16;
		Height 56;
		Mass 100;
		Speed 2;
		PainChance 160;
		Damage 0;
		XScale 1;
		YScale 1;
		-COUNTKILL
		+LOOKALLAROUND
		+FLOORCLIP
		+FRIENDLY
		+NOTAUTOAIMED
		+SLIDESONWALLS
		+DONTMORPH
		+NOBLOCKMONST
		+QUICKTORETALIATE
		+NOICEDEATH
		+BUDDHA
		+AVOIDMELEE
		MaxStepHeight 48;
		MaxDropOffHeight 48;
		PainSound "Iris/Pain";
		DamageFactor "FriendMarineDamage", 0;
	}
	
	override int TakeSpecialDamage(Actor inflictor, Actor source, int damage, Name damagetype)
	{
		if (source && (source.player || source is "Follower_Iris"))
		{
			return 0;
		}
		return super.TakeSpecialDamage(inflictor, source, damage, damagetype);
	}
	
	Override Void PostBeginPlay()
	{
		Super.PostBeginPlay();
		
		SecondaryOut = false;
		SetIdle = false;
		HealTimer = 0;
		
		PrimAmmo = 5;
		SecAmmo = 33;
		
		A_GiveInventory("IMAFRIENDLYDIPSHIT");
		
		A_StartSound("Iris/Spawn",CHAN_VOICE);
	}
	
	override void Tick() 
	{
		super.Tick();
		
		if (isFrozen())
		{
			return;
		}
		
		if(!master)
		{
			Spawn("TeleportFog", (pos.x, pos.y, pos.z + height * 0.5));
			Destroy();
			return;
		}
		
		if(health < default.health - 15 && HealTimer <= 0)
		{
			if(random(1,10) == 3) { A_Pain(); }
			A_StartSound("medkit/use",0);
			A_SetHealth(health + 15);
			HealTimer = random(70,140);
		}
		
		if (health <= 5 && !InStateSequence(curstate, FindState("FakeDeath")))
		{
			A_SetHealth(default.health);
			SetStateLabel("FakeDeath");
		}
		
		if(health <= default.health / 2 && target != master) { bFRIGHTENED = true; }
		else { bFRIGHTENED = false; }
		
		HealTimer--;
	}
	
	Override bool CanCollideWith(Actor other, bool Passive)
	{
		If(!Other) 
		Return False;
		If(Other && !Passive)
		{
			If(Other.Player)
			{
				If(!Deathmatch) 
				Return False;
				Else If(Deathmatch && Other == Master) 
				Return False;
			}			
			If(Other.bMISSILE && Other.Target && Other.Target.Player)
			{
				If(!Deathmatch) 
				Return False;
				Else If(Deathmatch && Other.Target == Master) 
				Return False;
			}			
			Return True;
		}
		If(Other && Passive)
		{
			If(Other.Player)
			{
				If(!Deathmatch) 
				Return False;
				Else If(Deathmatch && Other == Master) 
				Return False;
			}			
			If(Other.bMISSILE && Other.Target && Other.Target.Player)
			{
				If(!Deathmatch) 
				Return False;
				Else If(Deathmatch && Other.Target == Master) 
				Return False;
			}
			Return True;
		}
		Return True;
	}
	
	override bool Used(Actor user)
	{
		let plr = CODPlayer(user);
		
		if(InStateSequence(curstate, FindState("FakeDeath")))
		{
			//[Pop] Maybe spawn particles or something
			SetStateLabel("FakeRaise");
		}
		else
		{
			SetIdle = !SetIdle;
			if(SetIdle) { A_StartSound("Iris/Hold",CHAN_VOICE); }
			else { A_StartSound("Iris/Follow",CHAN_VOICE); }
			//[Pop] Invert This basically
		}
		
		return Super.Used(user);
	}
	
	action void Iris_Fire(bool which)
	{
		A_SpawnItemEx("PlayerMuzzleFlash",30,0,45);
		
		if(which)
		{
			A_StartSound("G18/fire", 0, CHANF_OVERLAP, 0.75);
			A_StartSound("G18/fireAdd", 0, CHANF_OVERLAP, 1);
			A_StartSound("G18/fireTail", 0, CHANF_OVERLAP, 0.5);
			A_SpawnProjectile("COD_9x19mm_Friendly", 46, 0, frandom(2.5,-2.5), CMF_AIMDIRECTION, self.pitch + frandom(-5,5));
			A_AlertMonsters(0,AMF_TARGETEMITTER);
			invoker.SecAmmo--;
		}
		else
		{
			A_StartSound("M24/Fire", 0, CHANF_OVERLAP, 1);
			A_SpawnProjectile("COD_762x51mm_Friendly", 46, 0, frandom(0.05,-0.05), CMF_AIMDIRECTION, self.pitch + frandom(-1,1));
			A_AlertMonsters(0,AMF_TARGETEMITTER);
			invoker.PrimAmmo--;
		}
	}
	
	States
	{
		Spawn:
			IRIS O 1 A_Look;
			TNT1 A 0 A_CheckSight("TeleTic");
			Loop;
		See:
			IRIS AAAAAABBBBBB 1
			{
				If (Master && Distance3D(master) < 70 || SetIdle)
				{
					Return ResolveState("Stand");
				}
				A_Chase();
				A_Recoil(-0.25);
				Return ResolveState(Null);
			}
			TNT1 A 0 A_StartSound("step/hard",0);
			IRIS CCCCCCDDDDDD 1
			{
				If (Master && Distance3D(master) < 128 || SetIdle)
				{
					Return ResolveState("Stand");
				}
				A_Chase();
				A_Recoil(-0.25);
				Return ResolveState(Null);
			}
			TNT1 A 0 A_StartSound("step/hard",0);
			TNT1 A 0 A_CheckSight("TeleTic");
			Loop;
		Stand:
			IRIS O 1
			{ 
				If (IdleTic >= GetCVar("CODF_idletalk"))
				{
					IdleTic = 0;
					A_StartSound("Iris/Idle", CHAN_VOICE);
				}
				IdleTic++;
				if(random(1,20) <= 3)
				{
					A_SetAngle(angle + random(-25,25));
				}
				A_Chase("Melee","Missile",CHF_NOPLAYACTIVE|CHF_DONTMOVE|CHF_NODIRECTIONTURN);
			}
			Goto See;
		TeleTic:
			TNT1 A 0 
			{
				if (teletic >= 15)
				{
					A_ClearTarget();
					teletic = 0;
					Warp(master, frandom(-16, -64), frandom(-64, 64), 0, 0, WARPF_STOP|WARPF_TOFLOOR);
				}
				teletic++;
			}
			Goto See;
		Melee:
			IRIS F 2 { SecondaryOut = true; }
			IRIS F 4 A_FaceTarget(0,90,0,0, FAF_MIDDLE);
		MeleeSkip:
			TNT1 A 0 A_JumpIf(SecAmmo <= 4, "Reload2");
			TNT1 A 0 A_Recoil(2);
			IRIS F 1 Bright 
			{
				IdleTic = 0;
				Iris_Fire(SecondaryOut);
				A_ChangeVelocity(random(-5,-10), random(-3,3), random(1,2),CVF_RELATIVE);
				A_Chase(NULL,NULL,CHF_FASTCHASE);
			}
			IRIS F 2 A_FaceTarget(0,90,0,0, FAF_MIDDLE);
			IRIS F 1 Bright Iris_Fire(SecondaryOut);
			IRIS F 2 A_FaceTarget(0,90,0,0, FAF_MIDDLE);
			IRIS F 1 Bright Iris_Fire(SecondaryOut);
			IRIS F 2 A_FaceTarget(0,90,0,0, FAF_MIDDLE);
			IRIS F 1 Bright Iris_Fire(SecondaryOut);
			IRIS F 2 A_FaceTarget(0,90,0,0, FAF_MIDDLE);
			IRIS F 1 Bright Iris_Fire(SecondaryOut);
			TNT1 A 0 A_jumpif(checklof() && target.Health > 0,"MeleeSkip");
			TNT1 A 0 A_Jump(128,"MeleeSkip");
			Goto See;
		
		Missile:
			TNT1 A 0 { SecondaryOut = false; }
			TNT1 A 0 A_JumpIf(PrimAmmo <= 0, "Reload");
			TNT1 A 0
			{
				if(random(1,10) == 5)
				{
					A_StartSound("Iris/Attack",CHAN_VOICE);
				}
				if(!SetIdle)
				{
					A_ChangeVelocity(random(-2,-10), random(-10,10), random(1,2),CVF_RELATIVE);
				}
			}
			TNT1 A 0 A_Jump(256, "Missile1");  
		Missile1:
			IRIS EEE 1 A_FaceTarget(0,90,0,0, FAF_TOP);
			IRIS E 1 Bright
			{	
				IdleTic = 0;
				Iris_Fire(SecondaryOut);
			}
			IRIS E 6;
			IRIS E 15 A_StartSound("M24/BoltBack", 0);
			IRIS E 15 A_StartSound("M24/BoltForward", 0);
			TNT1 A 0 A_Jump(128, "Missile1");
			Goto See;
		
		Reload:
			IRIS O 2;
			IRIS E 15 A_StartSound("M24/BoltBack", 0);
			IRIS OOOOO 10 A_StartSound("mosin/shell", 0, CHANF_OVERLAP, 1);
			IRIS E 15 A_StartSound("M24/BoltForward", 0);
			TNT1 A 0 { PrimAmmo = 5; SecondaryOut = false; }
			Goto See;
		Reload2:
			IRIS F 2;
			IRIS F 20 A_StartSound("G18/MagOut", 0);
			IRIS F 20 A_StartSound("G18/MagIn", 0);
			IRIS F 15 A_StartSound("G18/Charge", 0);
			TNT1 A 0 { SecAmmo = 33; SecondaryOut = true; }
			Goto See;
			
		Pain:
			IRIS G 8
			{
				A_Pain();
				A_ChangeVelocity(random(-5,5), random(-5,5), random(1,2),CVF_RELATIVE);
			}
			Goto See;
		Death:
		XDeath:
		FakeDeath:
			TNT1 A 0 
			{
				bSHOOTABLE = false;
			}
			IRIS G 5;
			TNT1 A 0 A_StartSound("Iris/Death");
			IRIS HIJKL 5;
			IRIS M -1;
		FakeRaise:
			TNT1 A 0 
			{
				A_StartSound("Iris/Spawn", CHAN_VOICE);
			}
			IRIS LKJIHG 5;
			TNT1 A 0
			{
				bSHOOTABLE = true;
			}
			Goto See;
    }
}

class Follower_Iris_Token : Inventory { Default { Inventory.MaxAmount 1; } }