class Follower_Meryl : actor
{
	Int TeleTic;	
	Int	IdleTic;
	Int HealTimer;
	
	Int PrimAmmo;
	Int SecAmmo;
	
	bool SecondaryOut;
	bool SetIdle;
	
	Default
	{
		Monster;
		Scale 0.75;
		Health 200;
		Radius 16;
		Height 42;
		Mass 100;
		Speed 2;
		PainChance 160;
		Damage 0;
		XScale 1;
		YScale 1;
		-COUNTKILL
		+LOOKALLAROUND
		+FLOORCLIP
		+FRIENDLY
		+NOTAUTOAIMED
		+SLIDESONWALLS
		+DONTMORPH
		+NOBLOCKMONST
		+QUICKTORETALIATE
		+NOICEDEATH
		+BUDDHA
		+AVOIDMELEE
		MaxStepHeight 48;
		MaxDropOffHeight 48;
		PainSound "Meryl/Pain";
		DamageFactor "FriendMarineDamage", 0;
	}
	
	override int TakeSpecialDamage(Actor inflictor, Actor source, int damage, Name damagetype)
	{
		if (source && (source.player || source is "Follower_Sakuya"))
		{
			return 0;
		}
		return super.TakeSpecialDamage(inflictor, source, damage, damagetype);
	}
	
	Override Void PostBeginPlay()
	{
		Super.PostBeginPlay();
		
		SecondaryOut = false;
		SetIdle = false;
		HealTimer = 0;
		
		PrimAmmo = 100;
		SecAmmo = 0;
		
		A_GiveInventory("IMAFRIENDLYDIPSHIT");
		
		A_StartSound("Meryl/Spawn",CHAN_VOICE);
	}
	
	override void Tick() 
	{
		super.Tick();
		
		if (isFrozen())
		{
			return;
		}
		
		if(SetIdle)
			height = 16;
		else
			height = default.height;
		
		if(!master)
		{
			Spawn("TeleportFog", (pos.x, pos.y, pos.z + height * 0.5));
			Destroy();
			return;
		}
		
		if(health < default.health - 15 && HealTimer <= 0)
		{
			if(random(1,10) == 3) { A_Pain(); }
			A_StartSound("medkit/use",0);
			A_SetHealth(health + 15);
			HealTimer = random(70,140);
		}
		
		if (health <= 5 && !InStateSequence(curstate, FindState("FakeDeath")))
		{
			A_SetHealth(default.health);
			SetStateLabel("FakeDeath");
		}
		
		if(health <= default.health / 2 && target != master) { bFRIGHTENED = true; }
		else { bFRIGHTENED = false; }
		
		HealTimer--;
	}
	
	Override bool CanCollideWith(Actor other, bool Passive)
	{
		If(!Other) 
		Return False;
		If(Other && !Passive)
		{
			If(Other.Player)
			{
				If(!Deathmatch) 
				Return False;
				Else If(Deathmatch && Other == Master) 
				Return False;
			}			
			If(Other.bMISSILE && Other.Target && Other.Target.Player)
			{
				If(!Deathmatch) 
				Return False;
				Else If(Deathmatch && Other.Target == Master) 
				Return False;
			}			
			Return True;
		}
		If(Other && Passive)
		{
			If(Other.Player)
			{
				If(!Deathmatch) 
				Return False;
				Else If(Deathmatch && Other == Master) 
				Return False;
			}			
			If(Other.bMISSILE && Other.Target && Other.Target.Player)
			{
				If(!Deathmatch) 
				Return False;
				Else If(Deathmatch && Other.Target == Master) 
				Return False;
			}
			Return True;
		}
		Return True;
	}
	
	override bool Used(Actor user)
	{
		let plr = CODPlayer(user);
		
		if(InStateSequence(curstate, FindState("FakeDeath")))
		{
			//[Pop] Maybe spawn particles or something
			SetStateLabel("FakeRaise");
		}
		else
		{
			SetIdle = !SetIdle;
			if(SetIdle) { A_StartSound("Meryl/Hold",CHAN_VOICE); }
			else { A_StartSound("Meryl/Follow",CHAN_VOICE); }
			SetStateLabel("FakeInteract");
			//[Pop] Invert This basically
		}
		
		return Super.Used(user);
	}
	
	action void Meryl_Fire()
	{
		A_SpawnItemEx("PlayerMuzzleFlash",30,0,45);
		
		A_StartSound("mg338/fire", 0, CHANF_OVERLAP, 1, ATTN_NORM, frandom(0.6, 0.8));
		A_StartSound("mg338/fireadd", 0, CHANF_OVERLAP, 0.65);
		if(SetIdle)
			A_SpawnProjectile("COD_338Lapua_Friendly", 6, 0, frandom(5,-5), CMF_AIMDIRECTION, self.pitch + frandom(-5,5));
		else
			A_SpawnProjectile("COD_338Lapua_Friendly", 30, 0, frandom(5,-5), CMF_AIMDIRECTION, self.pitch + frandom(-5,5));
		A_AlertMonsters(0,AMF_TARGETEMITTER);
		invoker.PrimAmmo--;
	}
	
	States
	{
		Spawn:
			MRYL O 1 A_Look;
			TNT1 A 0 A_CheckSight("TeleTic");
			Loop;
		See:
			MRYL AAAAAABBBBBB 1
			{
				If (Master && Distance3D(master) < 70)
				{
					Return ResolveState("Stand");
				}
				else if (SetIdle)
				{
					Return ResolveState("Prone");
				}
				A_Chase();
				A_Recoil(-0.15);
				Return ResolveState(Null);
			}
			TNT1 A 0 A_StartSound("step/hard",0);
			MRYL CCCCCCDDDDDD 1
			{
				If (Master && Distance3D(master) < 70)
				{
					Return ResolveState("Stand");
				}
				else if (SetIdle)
				{
					Return ResolveState("Prone");
				}
				A_Chase();
				A_Recoil(-0.15);
				Return ResolveState(Null);
			}
			TNT1 A 0 A_StartSound("step/hard",0);
			TNT1 A 0 A_CheckSight("TeleTic");
			Loop;
		Stand:
			MRYL O 1
			{ 
				If (IdleTic >= GetCVar("CODF_idletalk"))
				{
					IdleTic = 0;
					A_StartSound("Meryl/Idle", CHAN_VOICE);
				}
				IdleTic++;
				if(random(1,20) <= 3)
				{
					A_SetAngle(angle + random(-25,25));
				}
				A_Chase(Null,"Missile",CHF_NOPLAYACTIVE|CHF_DONTMOVE|CHF_NODIRECTIONTURN);
			}
			TNT1 A 0 A_Jump(25, "StandIdle");
			Goto See;
		StandIdle:
			MRYL OPQRSO 6;
			Goto Stand;
		Prone:
			MRYL F 1
			{ 
				If (IdleTic >= GetCVar("CODF_idletalk"))
				{
					IdleTic = 0;
					A_StartSound("Meryl/Idle", CHAN_VOICE);
				}
				IdleTic++;
				if(random(1,20) <= 3)
				{
					A_SetAngle(angle + random(-25,25));
				}
				A_Chase(Null,"Missile",CHF_NOPLAYACTIVE|CHF_DONTMOVE|CHF_NODIRECTIONTURN);
			}
			Goto See;
		FakeInteract:
			MRYL TUT 12;
			Goto See;
		
		TeleTic:
			TNT1 A 0
			{
				if (teletic >= 15)
				{
					A_ClearTarget();
					teletic = 0;
					Warp(master, frandom(-16, -64), frandom(-64, 64), 0, 0, WARPF_STOP|WARPF_TOFLOOR);
				}
				teletic++;
			}
			Goto See;
		Melee:
			MRYL E 2 A_JumpIf(SetIdle, "MeleeProne");
			TNT1 A 0 A_Recoil(2);
			MRYL E 4 A_FaceTarget(0,90,0,0, FAF_MIDDLE);
			MRYL E 1 Bright 
			{
				IdleTic = 0;
				A_ChangeVelocity(random(-1,-5), random(-3,3), random(1,2),CVF_RELATIVE);
				A_Chase(NULL,NULL,CHF_FASTCHASE);
			}
			Goto See;
		MeleeProne:
			MRYL F 4 A_FaceTarget(0,90,0,0, FAF_MIDDLE);
			MRYL F 1 Bright 
			{
				IdleTic = 0;
				A_Chase(NULL,NULL,CHF_FASTCHASE);
			}
			Goto See;
		
		Missile:
			TNT1 A 0 A_JumpIf(SetIdle, "MissileProne");
			TNT1 A 0 A_JumpIf(PrimAmmo <= 0, "Reload");
			TNT1 A 0
			{
				if(random(1,10) == 5)
				{
					A_StartSound("Meryl/Attack",CHAN_VOICE);
				}
				if(!SetIdle)
				{
					A_ChangeVelocity(random(2,10), random(-10,10), random(1,2),CVF_RELATIVE);
				}
			}
			TNT1 A 0 A_Jump(256, "Missile3", "Missile5");  
		Missile5:
			TNT1 A 0 A_JumpIf(PrimAmmo <= 4, "Reload");
			MRYL E 3 A_FaceTarget(0,90,0,0, FAF_MIDDLE);
			MRYL E 1 Bright 
			{	
				IdleTic = 0;
				Meryl_Fire();
			}
			MRYL E 4 A_FaceTarget(0,90,0,0, FAF_MIDDLE);
			MRYL E 1 Bright Meryl_Fire();
			MRYL E 4 A_FaceTarget(0,90,0,0, FAF_MIDDLE);
			MRYL E 1 Bright Meryl_Fire();
			MRYL E 4 A_FaceTarget(0,90,0,0, FAF_MIDDLE);
			MRYL E 1 Bright Meryl_Fire();
			MRYL E 4 A_FaceTarget(0,90,0,0, FAF_MIDDLE);
			MRYL E 1 Bright Meryl_Fire();
			TNT1 A 0 A_Jump(128, "Missile5", "Missile3");
			Goto See;
		Missile3:
			TNT1 A 0 A_JumpIf(PrimAmmo <= 2, "Reload");
			MRYL E 4 A_FaceTarget(0,90,0,0, FAF_MIDDLE);
			MRYL E 1 Bright 
			{	
				IdleTic = 0;
				Meryl_Fire();
			}
			MRYL E 4 A_FaceTarget(0,90,0,0, FAF_MIDDLE);
			MRYL E 1 Bright Meryl_Fire();
			MRYL E 4 A_FaceTarget(0,90,0,0, FAF_MIDDLE);
			MRYL E 1 Bright Meryl_Fire();
			TNT1 A 0 A_Jump(128, "Missile5", "Missile3");
			Goto See;
		MissileProne:
			TNT1 A 0 A_JumpIf(PrimAmmo <= 2, "ReloadProne");
			TNT1 A 0
			{
				if(random(1,10) == 5)
				{
					A_StartSound("Meryl/Attack",CHAN_VOICE);
				}
				if(!SetIdle)
				{
					A_ChangeVelocity(random(2,10), random(-10,10), random(1,2),CVF_RELATIVE);
				}
			}
			MRYL F 4 A_FaceTarget(0,90,0,0, FAF_MIDDLE);
			MRYL F 1 Bright 
			{	
				IdleTic = 0;
				Meryl_Fire();
			}
			MRYL F 4 A_FaceTarget(0,90,0,0, FAF_MIDDLE);
			MRYL F 1 Bright Meryl_Fire();
			MRYL F 4 A_FaceTarget(0,90,0,0, FAF_MIDDLE);
			MRYL F 1 Bright Meryl_Fire();
			TNT1 A 0 A_jumpif(checklof(),"MissileProne");
			Goto See;
		
		Reload:
			MRYL O 2;
			MRYL O 16 A_StartSound("mg338/LidOpen", 0);
			MRYL O 6 A_StartSound("mg338/Clear", 0);
			MRYL O 12 A_StartSound("mg338/BeltClear", 0);
			MRYL O 24 A_StartSound("mg338/ClearClose", 0);
			MRYL O 24 A_StartSound("mg338/BoxOff", 0);
			MRYL O 16 A_StartSound("mg338/BoxOn", 0);
			MRYL O 12 A_StartSound("mg338/BeltPlace", 0);
			MRYL O 24 A_StartSound("mg338/LidClose", 0);
			MRYL O 12 A_StartSound("mg338/BoltBack", 0);
			MRYL O 12 A_StartSound("mg338/BoltForward", 0);
			TNT1 A 0 { PrimAmmo = 100; }
			Goto See;
		ReloadProne:
			MRYL F 2;
			MRYL F 16 A_StartSound("mg338/LidOpen", 0);
			MRYL F 6 A_StartSound("mg338/Clear", 0);
			MRYL F 12 A_StartSound("mg338/BeltClear", 0);
			MRYL F 24 A_StartSound("mg338/ClearClose", 0);
			MRYL F 24 A_StartSound("mg338/BoxOff", 0);
			MRYL F 16 A_StartSound("mg338/BoxOn", 0);
			MRYL F 12 A_StartSound("mg338/BeltPlace", 0);
			MRYL F 24 A_StartSound("mg338/LidClose", 0);
			MRYL F 12 A_StartSound("mg338/BoltBack", 0);
			MRYL F 12 A_StartSound("mg338/BoltForward", 0);
			TNT1 A 0 { PrimAmmo = 100; }
			Goto See;
			
		Pain:
			MRYL G 8
			{
				A_Pain();
				A_ChangeVelocity(random(-2.5,2.5), random(-2.5,2.5), random(1,2),CVF_RELATIVE);
			}
			Goto See;
		Death:
		XDeath:
		FakeDeath:
			TNT1 A 0 
			{
				bSHOOTABLE = false;
			}
			MRYL G 5;
			TNT1 A 0 A_StartSound("Meryl/Death");
			MRYL HIJK 5;
			MRYL L -1;
		FakeRaise:
			TNT1 A 0 
			{
				A_StartSound("Meryl/Spawn", CHAN_VOICE);
			}
			MRYL KJIHG 5;
			TNT1 A 0
			{
				bSHOOTABLE = true;
			}
			Goto See;
    }
}

class Follower_Meryl_Token : Inventory { Default { Inventory.MaxAmount 1; } }